site_name: Code To Trade
site_url: https://docs.codetotrade.app
theme:
  name: material
  icon:
    logo: fontawesome/solid/code
  favicon: fontawesome/solid/code
  features:
    - navigation.expand
    - navigation.path
    - navigation.footer
extra:
  homepage: https://codetotrade.app  
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/codetotradeapp  
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:    
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html